export declare enum PaymentPurpose {
    WALLET_TOPUP = "WALLET_TOPUP",
    BOOKING = "BOOKING",
    MARKETPLACE_ORDER = "MARKETPLACE_ORDER",
    COURSE_ENROLLMENT = "COURSE_ENROLLMENT",
    GUIDANCE_PLAN = "GUIDANCE_PLAN"
}
export declare enum PaymentProvider {
    PAYSTACK = "PAYSTACK",
    FLUTTERWAVE = "FLUTTERWAVE"
}
