import { DEMO_USERS } from '@/demo';

export const DEMO_FORUM_CATEGORIES = [
  {
    id: 'demo-category-1',
    name: 'General Wisdom',
    slug: 'general-wisdom',
    description: 'Community reflections and spiritual guidance.',
    icon: '𓂀',
    threadCount: 2,
    isTeachings: false,
    isActive: true,
  },
  {
    id: 'demo-category-2',
    name: 'Ifá Teachings',
    slug: 'ifa-teachings',
    description: 'Curated teachings from elders (read-only).',
    icon: 'Ọ̀rúnmìlà',
    threadCount: 1,
    isTeachings: true,
    isActive: true,
  },
];

export const DEMO_FORUM_THREADS = [
  {
    id: 'demo-thread-1',
    categoryId: 'demo-category-1',
    authorId: 'demo-baba-1',
    title: 'Preparing for divination: mindset and offerings',
    content: 'Share how you prepare your spirit and space before sitting with a Babalawo.',
    status: 'ACTIVE',
    isPinned: true,
    isLocked: false,
    isApproved: true,
    viewCount: 128,
    postCount: 12,
    createdAt: '2026-02-01T12:00:00Z',
    author: {
      id: 'demo-baba-1',
      name: DEMO_USERS['demo-baba-1'].name,
      yorubaName: DEMO_USERS['demo-baba-1'].yorubaName,
      avatar: DEMO_USERS['demo-baba-1'].avatar,
      verified: true,
      culturalLevel: DEMO_USERS['demo-baba-1'].culturalLevel as string,
    },
    category: {
      id: 'demo-category-1',
      name: 'General Wisdom',
      slug: 'general-wisdom',
      isTeachings: false,
    },
  },
  {
    id: 'demo-thread-2',
    categoryId: 'demo-category-1',
    authorId: 'demo-client-1',
    title: 'Dream symbols: white cloth and water',
    content: 'I keep dreaming of white cloth by a river. What could this mean?',
    status: 'ACTIVE',
    isPinned: false,
    isLocked: false,
    isApproved: true,
    viewCount: 64,
    postCount: 8,
    createdAt: '2026-02-02T10:30:00Z',
    author: {
      id: 'demo-client-1',
      name: DEMO_USERS['demo-client-1'].name,
      yorubaName: DEMO_USERS['demo-client-1'].yorubaName,
      avatar: DEMO_USERS['demo-client-1'].avatar,
      verified: false,
      culturalLevel: DEMO_USERS['demo-client-1'].culturalLevel as string,
    },
    category: {
      id: 'demo-category-1',
      name: 'General Wisdom',
      slug: 'general-wisdom',
      isTeachings: false,
    },
  },
  {
    id: 'demo-thread-3',
    categoryId: 'demo-category-2',
    authorId: 'demo-baba-1',
    title: 'Understanding ìwà pẹ̀lẹ́ (gentle character)',
    content: 'An introduction to gentle character and its role in spiritual growth.',
    status: 'ACTIVE',
    isPinned: false,
    isLocked: true,
    isApproved: true,
    viewCount: 210,
    postCount: 3,
    createdAt: '2026-01-28T09:00:00Z',
    author: {
      id: 'demo-baba-1',
      name: DEMO_USERS['demo-baba-1'].name,
      yorubaName: DEMO_USERS['demo-baba-1'].yorubaName,
      avatar: DEMO_USERS['demo-baba-1'].avatar,
      verified: true,
      culturalLevel: DEMO_USERS['demo-baba-1'].culturalLevel as string,
    },
    category: {
      id: 'demo-category-2',
      name: 'Ifá Teachings',
      slug: 'ifa-teachings',
      isTeachings: true,
    },
  },
];

export const DEMO_FORUM_POSTS_BY_THREAD = {
  'demo-thread-1': [
    {
      id: 'demo-post-1',
      threadId: 'demo-thread-1',
      authorId: 'demo-client-1',
      content: 'I fast and sit quietly before sunrise. It helps me listen clearly.',
      status: 'ACTIVE',
      isEdited: false,
      acknowledgeCount: 3,
      createdAt: '2026-02-01T14:00:00Z',
      author: {
        id: 'demo-client-1',
        name: DEMO_USERS['demo-client-1'].name,
        yorubaName: DEMO_USERS['demo-client-1'].yorubaName,
        avatar: DEMO_USERS['demo-client-1'].avatar,
        verified: false,
      },
    },
    {
      id: 'demo-post-2',
      threadId: 'demo-thread-1',
      authorId: 'demo-baba-1',
      content: 'Bring water, kola, and a clear intention. Your honesty is the offering.',
      status: 'ACTIVE',
      isEdited: false,
      acknowledgeCount: 8,
      createdAt: '2026-02-01T15:30:00Z',
      author: {
        id: 'demo-baba-1',
        name: DEMO_USERS['demo-baba-1'].name,
        yorubaName: DEMO_USERS['demo-baba-1'].yorubaName,
        avatar: DEMO_USERS['demo-baba-1'].avatar,
        verified: true,
      },
    },
  ],
};
