import { z } from 'zod';
import { CourseStatus, LessonType, EnrollmentStatus, CourseLevel } from '../enums/academy.enum.js';
export declare const CourseSchema: z.ZodObject<{
    id: z.ZodString;
    instructorId: z.ZodString;
    title: z.ZodString;
    slug: z.ZodString;
    description: z.ZodString;
    category: z.ZodString;
    level: z.ZodNativeEnum<typeof CourseLevel>;
    thumbnail: z.ZodOptional<z.ZodString>;
    duration: z.ZodNullable<z.ZodNumber>;
    price: z.ZodNumber;
    currency: z.ZodDefault<z.ZodString>;
    status: z.ZodNativeEnum<typeof CourseStatus>;
    approvedBy: z.ZodOptional<z.ZodString>;
    enrolledCount: z.ZodDefault<z.ZodNumber>;
    lessonCount: z.ZodDefault<z.ZodNumber>;
    certificateEnabled: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    description: string;
    status: CourseStatus;
    title: string;
    category: string;
    currency: string;
    duration: number | null;
    price: number;
    slug: string;
    instructorId: string;
    level: CourseLevel;
    enrolledCount: number;
    lessonCount: number;
    certificateEnabled: boolean;
    thumbnail?: string | undefined;
    approvedBy?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    description: string;
    status: CourseStatus;
    title: string;
    category: string;
    duration: number | null;
    price: number;
    slug: string;
    instructorId: string;
    level: CourseLevel;
    currency?: string | undefined;
    thumbnail?: string | undefined;
    approvedBy?: string | undefined;
    enrolledCount?: number | undefined;
    lessonCount?: number | undefined;
    certificateEnabled?: boolean | undefined;
}>;
export type Course = z.infer<typeof CourseSchema>;
export declare const LessonSchema: z.ZodObject<{
    id: z.ZodString;
    courseId: z.ZodString;
    title: z.ZodString;
    order: z.ZodNumber;
    type: z.ZodNativeEnum<typeof LessonType>;
    content: z.ZodOptional<z.ZodString>;
    videoUrl: z.ZodOptional<z.ZodString>;
    audioUrl: z.ZodOptional<z.ZodString>;
    duration: z.ZodNullable<z.ZodNumber>;
    resources: z.ZodArray<z.ZodString, "many">;
    status: z.ZodDefault<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    type: LessonType;
    status: string;
    title: string;
    order: number;
    duration: number | null;
    courseId: string;
    resources: string[];
    content?: string | undefined;
    videoUrl?: string | undefined;
    audioUrl?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    type: LessonType;
    title: string;
    order: number;
    duration: number | null;
    courseId: string;
    resources: string[];
    content?: string | undefined;
    status?: string | undefined;
    videoUrl?: string | undefined;
    audioUrl?: string | undefined;
}>;
export type Lesson = z.infer<typeof LessonSchema>;
export declare const EnrollmentSchema: z.ZodObject<{
    id: z.ZodString;
    courseId: z.ZodString;
    studentId: z.ZodString;
    status: z.ZodNativeEnum<typeof EnrollmentStatus>;
    progress: z.ZodDefault<z.ZodNumber>;
    enrolledAt: z.ZodDate;
    completedAt: z.ZodNullable<z.ZodDate>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: EnrollmentStatus;
    studentId: string;
    completedAt: Date | null;
    courseId: string;
    progress: number;
    enrolledAt: Date;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: EnrollmentStatus;
    studentId: string;
    completedAt: Date | null;
    courseId: string;
    enrolledAt: Date;
    progress?: number | undefined;
}>;
export type Enrollment = z.infer<typeof EnrollmentSchema>;
export declare const LessonCompletionSchema: z.ZodObject<{
    id: z.ZodString;
    enrollmentId: z.ZodString;
    lessonId: z.ZodString;
    completedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    completedAt: Date;
    enrollmentId: string;
    lessonId: string;
}, {
    id: string;
    completedAt: Date;
    enrollmentId: string;
    lessonId: string;
}>;
export type LessonCompletion = z.infer<typeof LessonCompletionSchema>;
export declare const CourseCertificateSchema: z.ZodObject<{
    id: z.ZodString;
    enrollmentId: z.ZodString;
    certificateUrl: z.ZodString;
    issuedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    enrollmentId: string;
    certificateUrl: string;
    issuedAt: Date;
}, {
    id: string;
    enrollmentId: string;
    certificateUrl: string;
    issuedAt: Date;
}>;
export type CourseCertificate = z.infer<typeof CourseCertificateSchema>;
