import { z } from 'zod';
export declare const AppointmentSchema: z.ZodObject<{
    id: z.ZodString;
    babalawoId: z.ZodString;
    clientId: z.ZodString;
    date: z.ZodString;
    time: z.ZodString;
    timezone: z.ZodDefault<z.ZodString>;
    duration: z.ZodDefault<z.ZodNumber>;
    status: z.ZodEnum<["UPCOMING", "COMPLETED", "CANCELLED", "IN_SESSION"]>;
    price: z.ZodOptional<z.ZodNumber>;
    notes: z.ZodOptional<z.ZodString>;
    cancelledAt: z.ZodOptional<z.ZodDate>;
    cancelledBy: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: "UPCOMING" | "COMPLETED" | "CANCELLED" | "IN_SESSION";
    babalawoId: string;
    clientId: string;
    date: string;
    time: string;
    timezone: string;
    duration: number;
    notes?: string | undefined;
    cancelledAt?: Date | undefined;
    price?: number | undefined;
    cancelledBy?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: "UPCOMING" | "COMPLETED" | "CANCELLED" | "IN_SESSION";
    babalawoId: string;
    clientId: string;
    date: string;
    time: string;
    notes?: string | undefined;
    cancelledAt?: Date | undefined;
    timezone?: string | undefined;
    duration?: number | undefined;
    price?: number | undefined;
    cancelledBy?: string | undefined;
}>;
export type Appointment = z.infer<typeof AppointmentSchema>;
export declare const CreateAppointmentSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    babalawoId: z.ZodString;
    clientId: z.ZodString;
    date: z.ZodString;
    time: z.ZodString;
    timezone: z.ZodDefault<z.ZodString>;
    duration: z.ZodDefault<z.ZodNumber>;
    status: z.ZodEnum<["UPCOMING", "COMPLETED", "CANCELLED", "IN_SESSION"]>;
    price: z.ZodOptional<z.ZodNumber>;
    notes: z.ZodOptional<z.ZodString>;
    cancelledAt: z.ZodOptional<z.ZodDate>;
    cancelledBy: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "id" | "createdAt" | "updatedAt" | "status" | "clientId" | "cancelledAt" | "cancelledBy">, "strip", z.ZodTypeAny, {
    babalawoId: string;
    date: string;
    time: string;
    timezone: string;
    duration: number;
    notes?: string | undefined;
    price?: number | undefined;
}, {
    babalawoId: string;
    date: string;
    time: string;
    notes?: string | undefined;
    timezone?: string | undefined;
    duration?: number | undefined;
    price?: number | undefined;
}>;
export type CreateAppointmentDto = z.infer<typeof CreateAppointmentSchema>;
export declare const UpdateAppointmentSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    babalawoId: z.ZodOptional<z.ZodString>;
    clientId: z.ZodOptional<z.ZodString>;
    date: z.ZodOptional<z.ZodString>;
    time: z.ZodOptional<z.ZodString>;
    timezone: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    duration: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    status: z.ZodOptional<z.ZodEnum<["UPCOMING", "COMPLETED", "CANCELLED", "IN_SESSION"]>>;
    price: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    cancelledAt: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    cancelledBy: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt" | "babalawoId" | "clientId">, "strip", z.ZodTypeAny, {
    updatedAt?: Date | undefined;
    status?: "UPCOMING" | "COMPLETED" | "CANCELLED" | "IN_SESSION" | undefined;
    notes?: string | undefined;
    cancelledAt?: Date | undefined;
    date?: string | undefined;
    time?: string | undefined;
    timezone?: string | undefined;
    duration?: number | undefined;
    price?: number | undefined;
    cancelledBy?: string | undefined;
}, {
    updatedAt?: Date | undefined;
    status?: "UPCOMING" | "COMPLETED" | "CANCELLED" | "IN_SESSION" | undefined;
    notes?: string | undefined;
    cancelledAt?: Date | undefined;
    date?: string | undefined;
    time?: string | undefined;
    timezone?: string | undefined;
    duration?: number | undefined;
    price?: number | undefined;
    cancelledBy?: string | undefined;
}>;
export type UpdateAppointmentDto = z.infer<typeof UpdateAppointmentSchema>;
