import { z } from 'zod';
export declare const DocumentSchema: z.ZodObject<{
    id: z.ZodString;
    uploadedBy: z.ZodString;
    sharedWith: z.ZodString;
    type: z.ZodEnum<["document", "audio", "video", "image"]>;
    filename: z.ZodString;
    originalFilename: z.ZodString;
    size: z.ZodNumber;
    mimeType: z.ZodString;
    s3Key: z.ZodString;
    signedUrl: z.ZodOptional<z.ZodString>;
    urlExpiresAt: z.ZodOptional<z.ZodDate>;
    description: z.ZodOptional<z.ZodString>;
    scanned: z.ZodDefault<z.ZodBoolean>;
    encrypted: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    encrypted: boolean;
    createdAt: Date;
    type: "image" | "document" | "audio" | "video";
    filename: string;
    size: number;
    mimeType: string;
    s3Key: string;
    uploadedBy: string;
    sharedWith: string;
    originalFilename: string;
    scanned: boolean;
    description?: string | undefined;
    signedUrl?: string | undefined;
    urlExpiresAt?: Date | undefined;
}, {
    id: string;
    createdAt: Date;
    type: "image" | "document" | "audio" | "video";
    filename: string;
    size: number;
    mimeType: string;
    s3Key: string;
    uploadedBy: string;
    sharedWith: string;
    originalFilename: string;
    encrypted?: boolean | undefined;
    description?: string | undefined;
    signedUrl?: string | undefined;
    urlExpiresAt?: Date | undefined;
    scanned?: boolean | undefined;
}>;
export type Document = z.infer<typeof DocumentSchema>;
export declare const CreateDocumentSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    uploadedBy: z.ZodString;
    sharedWith: z.ZodString;
    type: z.ZodEnum<["document", "audio", "video", "image"]>;
    filename: z.ZodString;
    originalFilename: z.ZodString;
    size: z.ZodNumber;
    mimeType: z.ZodString;
    s3Key: z.ZodString;
    signedUrl: z.ZodOptional<z.ZodString>;
    urlExpiresAt: z.ZodOptional<z.ZodDate>;
    description: z.ZodOptional<z.ZodString>;
    scanned: z.ZodDefault<z.ZodBoolean>;
    encrypted: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
}, "id" | "encrypted" | "createdAt" | "s3Key" | "uploadedBy" | "signedUrl" | "urlExpiresAt" | "scanned">, "strip", z.ZodTypeAny, {
    type: "image" | "document" | "audio" | "video";
    filename: string;
    size: number;
    mimeType: string;
    sharedWith: string;
    originalFilename: string;
    description?: string | undefined;
}, {
    type: "image" | "document" | "audio" | "video";
    filename: string;
    size: number;
    mimeType: string;
    sharedWith: string;
    originalFilename: string;
    description?: string | undefined;
}>;
export type CreateDocumentDto = z.infer<typeof CreateDocumentSchema>;
