import { z } from 'zod';
import { ThreadStatus, PostStatus } from '../enums/forum.enum.js';
export declare const ForumCategorySchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    slug: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    icon: z.ZodOptional<z.ZodString>;
    order: z.ZodDefault<z.ZodNumber>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    isTeachings: z.ZodDefault<z.ZodBoolean>;
    threadCount: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    name: string;
    updatedAt: Date;
    order: number;
    slug: string;
    isActive: boolean;
    isTeachings: boolean;
    threadCount: number;
    description?: string | undefined;
    icon?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    name: string;
    updatedAt: Date;
    slug: string;
    description?: string | undefined;
    order?: number | undefined;
    icon?: string | undefined;
    isActive?: boolean | undefined;
    isTeachings?: boolean | undefined;
    threadCount?: number | undefined;
}>;
export type ForumCategory = z.infer<typeof ForumCategorySchema>;
export declare const ForumThreadSchema: z.ZodObject<{
    id: z.ZodString;
    categoryId: z.ZodString;
    authorId: z.ZodString;
    title: z.ZodString;
    content: z.ZodString;
    status: z.ZodDefault<z.ZodNativeEnum<typeof ThreadStatus>>;
    isPinned: z.ZodDefault<z.ZodBoolean>;
    isLocked: z.ZodDefault<z.ZodBoolean>;
    isApproved: z.ZodDefault<z.ZodBoolean>;
    viewCount: z.ZodDefault<z.ZodNumber>;
    postCount: z.ZodDefault<z.ZodNumber>;
    lastPostAt: z.ZodOptional<z.ZodDate>;
    lastPostBy: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    content: string;
    createdAt: Date;
    updatedAt: Date;
    status: ThreadStatus;
    title: string;
    categoryId: string;
    authorId: string;
    isPinned: boolean;
    isLocked: boolean;
    isApproved: boolean;
    viewCount: number;
    postCount: number;
    lastPostAt?: Date | undefined;
    lastPostBy?: string | undefined;
}, {
    id: string;
    content: string;
    createdAt: Date;
    updatedAt: Date;
    title: string;
    categoryId: string;
    authorId: string;
    status?: ThreadStatus | undefined;
    isPinned?: boolean | undefined;
    isLocked?: boolean | undefined;
    isApproved?: boolean | undefined;
    viewCount?: number | undefined;
    postCount?: number | undefined;
    lastPostAt?: Date | undefined;
    lastPostBy?: string | undefined;
}>;
export type ForumThread = z.infer<typeof ForumThreadSchema>;
export declare const ForumPostSchema: z.ZodObject<{
    id: z.ZodString;
    threadId: z.ZodString;
    authorId: z.ZodString;
    content: z.ZodString;
    status: z.ZodDefault<z.ZodNativeEnum<typeof PostStatus>>;
    isEdited: z.ZodDefault<z.ZodBoolean>;
    editedAt: z.ZodOptional<z.ZodDate>;
    acknowledgeCount: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    content: string;
    createdAt: Date;
    updatedAt: Date;
    status: PostStatus;
    acknowledgeCount: number;
    threadId: string;
    authorId: string;
    isEdited: boolean;
    editedAt?: Date | undefined;
}, {
    id: string;
    content: string;
    createdAt: Date;
    updatedAt: Date;
    threadId: string;
    authorId: string;
    status?: PostStatus | undefined;
    acknowledgeCount?: number | undefined;
    isEdited?: boolean | undefined;
    editedAt?: Date | undefined;
}>;
export type ForumPost = z.infer<typeof ForumPostSchema>;
