import { z } from 'zod';
import { VendorStatus, ProductStatus, OrderStatus, ProductType, VerifiedTier } from '../enums/marketplace.enum.js';
export declare const VendorSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodString;
    businessName: z.ZodString;
    businessLicense: z.ZodOptional<z.ZodString>;
    taxId: z.ZodOptional<z.ZodString>;
    status: z.ZodNativeEnum<typeof VendorStatus>;
    endorsementBy: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    verifiedAt: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: VendorStatus;
    userId: string;
    businessName: string;
    description?: string | undefined;
    endorsementBy?: string | undefined;
    verifiedAt?: Date | undefined;
    businessLicense?: string | undefined;
    taxId?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: VendorStatus;
    userId: string;
    businessName: string;
    description?: string | undefined;
    endorsementBy?: string | undefined;
    verifiedAt?: Date | undefined;
    businessLicense?: string | undefined;
    taxId?: string | undefined;
}>;
export type Vendor = z.infer<typeof VendorSchema>;
export declare const ProductSchema: z.ZodObject<{
    id: z.ZodString;
    vendorId: z.ZodString;
    name: z.ZodString;
    category: z.ZodString;
    type: z.ZodNativeEnum<typeof ProductType>;
    description: z.ZodString;
    longDescription: z.ZodOptional<z.ZodString>;
    price: z.ZodNumber;
    currency: z.ZodDefault<z.ZodString>;
    stock: z.ZodNullable<z.ZodNumber>;
    images: z.ZodArray<z.ZodString, "many">;
    provenance: z.ZodOptional<z.ZodString>;
    usageProtocol: z.ZodOptional<z.ZodString>;
    status: z.ZodNativeEnum<typeof ProductStatus>;
    approvedBy: z.ZodOptional<z.ZodString>;
    verifiedTier: z.ZodNativeEnum<typeof VerifiedTier>;
    taxCompliant: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    name: string;
    updatedAt: Date;
    description: string;
    type: ProductType;
    status: ProductStatus;
    category: string;
    vendorId: string;
    currency: string;
    price: number;
    images: string[];
    stock: number | null;
    verifiedTier: VerifiedTier;
    taxCompliant: boolean;
    approvedBy?: string | undefined;
    longDescription?: string | undefined;
    provenance?: string | undefined;
    usageProtocol?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    name: string;
    updatedAt: Date;
    description: string;
    type: ProductType;
    status: ProductStatus;
    category: string;
    vendorId: string;
    price: number;
    images: string[];
    stock: number | null;
    verifiedTier: VerifiedTier;
    currency?: string | undefined;
    approvedBy?: string | undefined;
    longDescription?: string | undefined;
    provenance?: string | undefined;
    usageProtocol?: string | undefined;
    taxCompliant?: boolean | undefined;
}>;
export type Product = z.infer<typeof ProductSchema>;
export declare const OrderSchema: z.ZodObject<{
    id: z.ZodString;
    customerId: z.ZodString;
    vendorId: z.ZodString;
    status: z.ZodNativeEnum<typeof OrderStatus>;
    totalAmount: z.ZodNumber;
    currency: z.ZodDefault<z.ZodString>;
    taxAmount: z.ZodNullable<z.ZodNumber>;
    shippingCost: z.ZodNullable<z.ZodNumber>;
    shippingAddress: z.ZodOptional<z.ZodString>;
    paymentMethod: z.ZodOptional<z.ZodString>;
    paymentId: z.ZodOptional<z.ZodString>;
    paidAt: z.ZodNullable<z.ZodDate>;
    shippedAt: z.ZodNullable<z.ZodDate>;
    deliveredAt: z.ZodNullable<z.ZodDate>;
    cancelledAt: z.ZodNullable<z.ZodDate>;
    notes: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: OrderStatus;
    customerId: string;
    vendorId: string;
    totalAmount: number;
    currency: string;
    taxAmount: number | null;
    shippingCost: number | null;
    paidAt: Date | null;
    shippedAt: Date | null;
    deliveredAt: Date | null;
    cancelledAt: Date | null;
    notes?: string | undefined;
    shippingAddress?: string | undefined;
    paymentMethod?: string | undefined;
    paymentId?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: OrderStatus;
    customerId: string;
    vendorId: string;
    totalAmount: number;
    taxAmount: number | null;
    shippingCost: number | null;
    paidAt: Date | null;
    shippedAt: Date | null;
    deliveredAt: Date | null;
    cancelledAt: Date | null;
    notes?: string | undefined;
    currency?: string | undefined;
    shippingAddress?: string | undefined;
    paymentMethod?: string | undefined;
    paymentId?: string | undefined;
}>;
export type Order = z.infer<typeof OrderSchema>;
export declare const OrderItemSchema: z.ZodObject<{
    id: z.ZodString;
    orderId: z.ZodString;
    productId: z.ZodString;
    quantity: z.ZodNumber;
    price: z.ZodNumber;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    orderId: string;
    price: number;
    productId: string;
    quantity: number;
}, {
    id: string;
    createdAt: Date;
    orderId: string;
    price: number;
    productId: string;
    quantity: number;
}>;
export type OrderItem = z.infer<typeof OrderItemSchema>;
export declare const ProductReviewSchema: z.ZodObject<{
    id: z.ZodString;
    productId: z.ZodString;
    customerId: z.ZodString;
    rating: z.ZodNumber;
    title: z.ZodOptional<z.ZodString>;
    content: z.ZodOptional<z.ZodString>;
    acknowledgeCount: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: string;
    customerId: string;
    productId: string;
    rating: number;
    acknowledgeCount: number;
    content?: string | undefined;
    title?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    customerId: string;
    productId: string;
    rating: number;
    content?: string | undefined;
    status?: string | undefined;
    title?: string | undefined;
    acknowledgeCount?: number | undefined;
}>;
export type ProductReview = z.infer<typeof ProductReviewSchema>;
